apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: deploy-app-pipeline
  description: "openshift-pipeline"
  title: deploy-app-pipeline
  annotations:
    janus-idp.io/tekton: deploy-app-pipeline
    tektonci/build-namespace: backstage
    github.com/project-slug: jay2tinku/tekton-rhdh
    backstage.io/kubernetes-id: backstage
    argocd/app-name: deploy-app-pipeline
  tags:
    - tekton
    - argocd
    - sonarqube
spec:
  type: service
  owner: dev-hub-team
  lifecycle: experimental
  system: Pipeline
